cafe/urls.py
from django.urls import path
from . import views

app_name='cafe'

urlpatterns=[
    path('',views.IndexView.as_view(),name='index')
]

func_sample/diary/urls.py
from django.urls import path
from . import views

app_name='diary'

urlpatterns=[
    path("",views.index,name='index'),
    path('add/',views.add,name='add'),
    path('update/<int:pk>',views.update,name='update'),
    path('delete/<int:pk>',views.delete,name='delete'),
    path('detail/<int:pk>',views.detail,name='detail'),
]

project/diary/urls.py
from django.urls import path
from . import views

app_name='diary'

urlpatterns=[
    path("",views.indexView.as_view(),name='index'),
    path('add/',views.AddView.as_view(),name='add'),
    path('update/<int:pk>',views.UpdateView.as_view(),name='update'),
    path('delete/<int:pk>',views.DeleteView.as_view(),name='delete'),
    path('detail/<int:pk>',views.DetailView.as_view(),name='detail'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary/',include('diary.urls')),
]

func_sample/diary/models.py
from django.db import models
from django.utils import timezone

class Day(models.Model):
    id=models.AutoField(primary_key=True)
    title=models.CharField('タイトル',max_length=20)
    text=models.TextField('本文')
    date=models.DateTimeField('日付',default=timezone.now)

project/diary/models.py
from django.db import models
from django.utils import timezone

class Day(models.Model):
    id=models.AutoField(primary_key=True)
    title=models.CharField('タイトル',max_length=20)
    text=models.TextField('本文')
    date=models.DateTimeField('日付',default=timezone.now)

    def __str__(self):
        return self.title

func_sample/diary/forms.py
from django import forms
from .models import Day

class DayCreateForm(forms.ModelForm):

    class Meta:
        model=Day
        fields='__all__'

project/diary/forms.py
from django import forms
from .models import Day

class DayCreateForm(forms.ModelForm):

    class Meta:
        model=Day
        fields='__all__'

func_sample/diary/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import DayCreateForm
from .models import Day

def index(request):
    context={
        'day_list':Day.objects.all(),
    }
    return render(request,'diary/day_list.html',context)

def add(request):
    form=DayCreateForm(request.POST or None)

    if request.method=='POST' and form.is_valid():
        form.save()
        return redirect('diary:index')

    context={
        'form':form
    }
    return render(request,'diary/day_form.html',context)

def update(request,pk):
    day=get_object_or_404(Day,pk=pk)

    form=DayCreateForm(request.POST or None,instance=day)

    if request.method=='POST' and form.is_valid():
        form.save()
        return redirect('diary:index')

    context={
        'form':form
    }

    return render(request,'diary/day_form.html',context)


def delete(request,pk):
    day=get_object_or_404(Day,pk=pk)

    if request.method=='POST':
        day.delete()
        return redirect('diary:index')

    context={
        'day':day,
    }

    return render(request,'diary/day_confirm_delete.html',context)


def detail(request,pk):
    day=get_object_or_404(Day,pk=pk)

    context={
        'day':day,
    }

    return render(request,'diary/day_detail.html',context)

project/diary/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render,redirect,get_object_or_404
from django.urls import reverse_lazy
from django.views import generic
from .forms import DayCreateForm
from .models import Day

class indexView(generic.ListView):
    model=Day
    paginate_by=3

class AddView(LoginRequiredMixin,generic.CreateView):
    model=Day
    form_class=DayCreateForm
    success_url=reverse_lazy('diary:index')

class UpdateView(LoginRequiredMixin,generic.UpdateView):
    model=Day
    form_class=DayCreateForm
    success_url=reverse_lazy('diary:index')

class DeleteView(LoginRequiredMixin,generic.DeleteView):
    model=Day
    success_url=reverse_lazy('diary:index')

class DetailView(generic.DetailView):
    model=Day

func_sample/diary/templates/diary/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>  {% block title %}
      {% endblock %}</title>
  </head>
  <body>
    <div class="container">
      <nav class="nav">
       <a class="nav-link active" href="{% url 'diary:index' %}">一覧</a>
       <a class="nav-link" href="{% url 'diary:add' %}">追加</a>
      </nav>
      {% block content %}
      {% endblock %}
   </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

func_sample/diary/templates/diary/day_confirm_delete.html
{% extends 'diary/base.html' %}

{% block title %}
日記帳削除
{% endblock %}

{% block content %}
  <form action="" method="POST">
   <table class="table">
    <thead class="thead-light">
      <tr>
        <th>タイトル</th>
        <th>{{day.title}}</th>
      </tr>
      <tr>
        <th>本文</th>
        <th>{{day.text}}</th>
      </tr>
      <tr>
        <th>日付</th>
        <th>{{day.date}}</th>
      </tr>
    </table>
    <p>こちらのデータを削除します。</p>
    <button type="submit" class="bin-bin-primary">削除</button>
    {% csrf_token %}
  </form>
{% endblock %}

func_sample/diary/templates/diary/day_detail.html
{% extends 'diary/base.html' %}

{% block title %}
日記帳削除
{% endblock %}

{% block content %}
   <table class="table">
    <thead class="thead-light">
      <tr>
        <th>タイトル</th>
        <th>{{day.title}}</th>
      </tr>
      <tr>
        <th>本文</th>
        <th>{{day.text | linebreaksbr | urlize}}</th>
      </tr>
      <tr>
        <th>日付</th>
        <th>{{day.date}}</th>
      </tr>
    </table>
{% endblock %}

func_sample/diary/templates/diary/day_form.html
{% extends 'diary/base.html' %}

{% block title %}
日記入力画面
{% endblock %}

{% block content %}
<form action="" method="POST">
{{form.as_p}}
<button type="submit" class="bin-bin-primary">送信</button>
{% csrf_token %}
</form>
{% endblock %}

func_sample/diary/templates/diary/day_list.html
{% extends 'diary/base.html' %}

{% block title %}
日記帳一覧
{% endblock %}

{% block content %}
<h1>日記一覧</h1>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th>タイトル</th>
      <th>日付</th>
      <th>更新</th>
      <th>削除</th>
    </tr>
  </thead>
  <tbody>
    {% for day in day_list %}
    <tr>
      <td><a href="{% url 'diary:detail' day.id %}">{{day.title}}</a></td>
      <td>{{day.date}}</td>
      <td><a href="{% url 'diary:update' day.id %}">更新</a></td>
      <td><a href="{% url 'diary:delete' day.id %}">削除</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}